disabled_rules:
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - inclusive_language
  - large_tuple
  - line_length
  - nesting
  - type_name
  - todo

opt_in_rules:
  - colon
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - contains_over_filter_is_empty
  - empty_count
  - implicit_return
  - unneeded_parentheses_in_closure_argument

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - scripts

allow_zero_lintable_files: true

######## RULES ########

colon:
  severity: error
contains_over_filter_count: error
contains_over_filter_is_empty: error
contains_over_first_not_nil: error
contains_over_range_nil_comparison: error

force_cast: warning
force_try: warning

implicit_getter: error
identifier_name:
  excluded:
    - id
    - i
    - e

multiple_closures_with_trailing_closure: error
statement_position:
  severity: error
trailing_semicolon: error
unneeded_parentheses_in_closure_argument: warning
